; PlatformIO Project Configuration File
; Project: Herb_Garden_Node (IoT FYP)
; Author: Johnny
; Standard: US English / Professional Modular Setup

[env:rpipicow]
; --- CORE CONFIGURATION ---
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipicow
framework = arduino

; --- UPLOAD & DEBUG CONFIGURATION ---
upload_protocol = picotool
upload_port = *

; --- SERIAL MONITOR CONFIGURATION ---
monitor_speed = 115200
monitor_filters = time, colorize

; --- LIBRARY DEPENDENCIES ---
lib_deps = 
    adafruit/DHT sensor library @ ^1.4.7
    adafruit/Adafruit Unified Sensor @ ^1.1.15
    bblanchon/ArduinoJson @ ^7.4.3
    rweather/Crypto @ ^0.4.0

; --- BUILD OPTIONS ---
build_flags = 
    -I include
    -Wno-cpp